### ISSUE TITLE
Why node names have spaces removed?

### ISSUE THREAD

**Issue by guignonv** [veg/phylotree.js#105]
I wonder why spaces are being removed from node names. It appears to be done on purpose (lines 2964, 3022-3024) but I don't understand the reason and there are no comment explaining why.
I have trees with node names mixing spaces and underscores and they don't display well with spaces being removed. Would it be a problem to keep spaces in node labels?

**Comment by spond** [comment]
Dear @guignonv,

Newick format doesn't have as far as I know a **gold standard** reference for how the grammar is defined. In our implementation, you can retain spaces by including the name of the taxon in quotes; otherwise white spaces are ignored. One example of why we may want to do this is the following tree

```
(A , (B,    C),
D,
E)
```

Retaining spaces in labels would be 

```
"A "
"B"
"  C"
"
D"
"
E"
```

Best,
Sergei
