### ISSUE TITLE
Adding any method

### ISSUE THREAD

**Issue by SonofLastPanda** [veg/phylotree.js#113]
For a project, we are trying to add some methods. However, the methods that we are adding to main.js are not transferred to phylotree.js therefore they are not executed. How can we transfer the method to phylotree.js?

**Comment by stevenweaver** [comment]
Hi @SonofLastPanda, 

I hope that your username isn't true, otherwise you should be in a zoo under tight supervision instead of developing for phylotree.js!

We are currently actively migrating phylotree.js to es6 for easier extension of the package. Keep a lookout for version `1.0.0` when it is released. Until then, you will need to extend `d3.layout.phylotree` with your custom function like so 

https://github.com/veg/phylotree.js/blob/master/src/main.js#L3212

If you send me an example of what you are trying to do, I might be able to help more. 

Wishing the best for the survival of your species,
Steven
