### ISSUE TITLE
Implementation of a 'mouseover' functionality

### ISSUE THREAD

**Issue by lubwen** [veg/phylotree.js#123]
Hi All,

I am adopting phylotree for the display of a set of compounds with similar chemical structures. Each leaf node will be a compound. I would like to be able to display the chemical structure (and some additional information) for the compound when I mouseover a leaf node. However, I could not locate such functionality. I am wondering whether I should implement this myself or I should request such a feature/functionality to be added to phylotree. If someone can point me to the right direction it would be great.  

Thank you very much.

**Comment by stephenshank** [comment]
Dear @lubwen,

This can be achieved with the [style_nodes](http://phylotree.hyphy.org/documentation/nodes_branches.html?highlight=traverse_and_compute#phylotree.style_nodes) method of a `phylotree` object, prior to calling the `layout` method. This method allows the developer to write a custom function to be invoked on each node. From this function one can access both the corresponding DOM element as a `d3` selection and the underlying node data.

I've implemented a simple text change on the mouseover event in [this notebook](https://observablehq.com/@stephenshank/phylotree-js-mouseover). The main lines of code to pay attention to are 
```
.style_nodes(function(element, data) {
  element.on('mouseover', function() {
    d3.select('#mouseover-text')
      .text(data.name);
    });
  })
```

Please let me know if you have any additional questions. Also, we would be delighted if you'd be willing to share the product once it is finished! This is definitely a fascinating use case.

Best,
Stephen

**Comment by lubwen** [comment]
Dear @stephenshank,

Thanks a lot for your reply and example implementation. For some reason, I was not able to view the source code of your observablehq notebook. I am new to observablehq. I usually use 'Control-U' to view page source. I do not see anything that is related to '.style_nodes' on your notebook when I pressed 'Ctrl-U'. Do I need to do something different to view your source code? Is it possible that you post your source code here?

Thanks a lot again. Best regards,

Wen

**Comment by lubwen** [comment]
Dear @stephenshank,

Although I was not able to view the source code on observablehq, I was able to get come code to work by using the key lines of code you posted above. Thus it is not necessary for you to post your entire code here. 

Thanks again. Best regards,

Wen

**Comment by lubwen** [comment]
Hi Again,

This is not related to the 'mouseover' functionality but I think I would like to ask the question here . Currently I am having an issue displaying the tree in proper SVG size upon initial page load. Please see the link below:

http://lubw.com/phylotree/index.php

I am setting the width of the SVG to be 800 px and the height 600 px. However, upon page load, the width is 304 px and height is 517 px.

Does anyone have a clue of why the SVG dimension changed to 304 x 517 upon page load? How can I force it to display in 800 x 600?

Strangely, if I click on any of the buttons above the tree, the SVG dimension will become approximately 800 x 600.

Thanks a lot.

**Comment by stephenshank** [comment]
Dear @lubwen,

Please trying setting the options `'left-right-spacing'` and `'top-bottom-spacing'` to `'fit-to-size'`, as in the [phylo-bar example](https://github.com/veg/phylotree.js/blob/master/examples/phylo-bar/index.html#L135), then calling the `size` option.

This should size the SVG as desired. The phylotree object itself is usually slightly smaller, due to padding and axes.

Note that the default for both of these is `'fixed-step'` (as described in the [options page](http://phylotree.hyphy.org/documentation/options.html)). In the vertical case, this will try to set the height of the SVG based on a fixed amount of pixels per node, thus making height dependent on the number of nodes. This could explain the behavior you're seeing.

Also, feel free to open as many issues as you like! We'll try to respond as best and promptly as we can. Separate, new issues can definitely help other users who are experiencing similar issues and searching based on titles.

Best,
Stephen

**Comment by lubwen** [comment]
Dear @stephenshank,

Thanks a lot. It works!

Best regards,
Wen
