### ISSUE TITLE
Expand functionality of tree view

### ISSUE THREAD

**Issue by MyNameIsOka** [veg/phylotree.js#131]
Hello everybody,

I want to expand the functionality of my current implementation, which is a simple view based on the hello world example. I previously asked about that implementation, which has been resolved already: https://github.com/veg/phylotree.js/issues/129

The functionality that I would like to implement are expanding/shrinking, etc. of the phylotree view, similar to the given example: http://phylotree.hyphy.org/
![image](https://user-images.githubusercontent.com/18796117/68568577-49a3bc80-049f-11ea-900a-900706aa8e18.png)

I tried to use the provided code but I can't get it to work with the implementation from issue 129

When adjusting the code, it fails at d3.layout.pyhlotree("body"). 
![image](https://user-images.githubusercontent.com/18796117/68568712-b9b24280-049f-11ea-9bec-8b828405c84c.png)
It seems that "layout" has been changed with the newest implementation

The code snippet I used was:
```
let width  = 800; // $(container_id).width(),
          let height = 600; // $(container_id).height()
          let selection_set = ['Foreground'];
          let current_selection_name = $('#selection_name_box').val();
          let current_selection_id = 0;
          let max_selections = 10;
          let color_scheme = d3.scale.category10();
          let selection_menu_element_action = 'phylotree_menu_element_action';

          let tree = d3.layout.phylotree('body')
          .size([height, width])
          .separation(function (a,b) {return 0;})
          .count_handler (function (count) {
            $('#selected_branch_counter').text (function (d) {return count[current_selection_name];});
            $('#selected_filtered_counter').text (count.tag);
          });
          const container_id = '#tree_container';
          const svg = d3.select(container_id).append('svg')
              .attr('width', width)
              .attr('height', height);

          tree(data).svg (svg).layout();
```

Your help is much appreciated!

**Comment by stephenshank** [comment]
Dear @MyNameIsOka,

If you're using version 1.0.0-alpha as in #129, you're best off trying to follow [the homepage from the corresponding branch](https://github.com/veg/phylotree.js/blob/1.0.0-alpha/index.html), rather than any code found on http://phylotree.hyphy.org. Code on the latter site corresponds to the 0.x.x versions, and as you've noted there are many breaking changes. We're in the midst of a major version release, so everything is not completely in sync.

To access the future homepage which utilizes version 1.0.0-alpha, you can clone the repo, checkout that branch, install node_modules, then run `yarn build` or `npm build`, and serve the content with [http-server](https://www.npmjs.com/package/http-server).

Please let me know if you encounter any issues.

Best,
Stephen

**Comment by MyNameIsOka** [comment]
Hello Stephen,

thank you for your quick reply and your help.
I will try that way and will let you know how it went.

**Comment by MyNameIsOka** [comment]
Okay, I am stuck at spacing_x and spacing_y. 
I can't get this function to run and I can't find it in the current main.js file. 

The way I wanted to do it is creating the buttons as per the picture in my first message. When clicking the button i wanted to call spacing_x and spacing_y from main.js respectively and increase/decrease the spacing.

Could you please give me a pointer to into the right direction, @stephenshank ?

**Comment by stephenshank** [comment]
Dear @MyNameIsOka,

It appears to be [these lines](https://github.com/veg/phylotree.js/blob/1.0.0-alpha/index.html#L365) which attach click handlers for expansion and contraction in both directions.

Much of the render functionality seems to have been moved to the [TreeRender class](https://github.com/veg/phylotree.js/blob/1.0.0-alpha/src/render/draw.js#L23), with a singleton instance [attached to tree.display](https://github.com/veg/phylotree.js/blob/1.0.0-alpha/src/main.js#L278). Since [JavaScript class methods are not automatically bound to the instance](https://esdiscuss.org/topic/why-are-es6-class-methods-not-automatically-bound-to-the-instance), this explains the new call to `bind`.

Hope this helps!

Best,
Stephen

**Comment by MyNameIsOka** [comment]
Thanks a lot @stephenshank !
I got it working now. That was quite a struggle as I didn't want to use jquery.

**Comment by stephenshank** [comment]
Glad to help!
