### ISSUE TITLE
Export in svg

### ISSUE THREAD

**Issue by jpsglouzon** [veg/phylotree.js#14]
Dear @spond,

I would like to easily export the generated tree in svg or png. How could i do that since i am relatively new in javascript.

Thanks in advance

**Comment by stevenweaver** [comment]
Hello @jpsglouzon,

Is this for your own application? 
I've written a function that exports svg html elements to png or an svg. 

Please see the function definition here:
https://github.com/veg/hyphy-vision/blob/master/src/datamonkey/datamonkey.js#L33

You would use the function like so (`#tree_container` is the id of the svg):

```

           $("#export-phylo-svg").on('click', function(e) {
               datamonkey.save_image("svg", "#tree_container");
           });
           $("#export-phylo-png").on('click', function(e) {
               datamonkey.save_image("png", "#tree_container");
           });
```

Please note that you would need to add 
```
    <img id="hyphy-chart-image" />
    <canvas id="hyphy-chart-canvas"></canvas>
```
to your html page. You can use css to ensure that the display is none for these elements. 

I will update the function so that you will not need to do add those elements manually in the future.
If you're using the app on github pages, I can add a new button for svg/png exports. 

Best,
Steven

**Comment by jpsglouzon** [comment]
Dear @stevenweaver,

Yes, this is for my appliccation, that i will release soon on github.

It (the export button) works just perfectly. :-)

Thank you very much.
