### ISSUE TITLE
Color subtrees according to clusters

### ISSUE THREAD

**Issue by jpsglouzon** [veg/phylotree.js#15]
Dear @spond,

The example here (http://bl.ocks.org/spond/dbc459acfaa6f134c67d) is pretty useful. Is there a way to not only color the leaves but the subtres corresponding to the clusters.

Thanks

**Comment by spond** [comment]
Dear @jpsglouzon,

Yes, it can be done, but because you only label the terminal branches, you need to decide how to propagate the colors up the tree. For example, how do you color this subtree, where one of the terminal branches has no assignment (or belongs to a different cluster)?

![screen shot 2016-03-10 at 1 15 35 pm](https://cloud.githubusercontent.com/assets/1018513/13684816/47aa1aea-e6c2-11e5-83e8-2bdd6bba53aa.png)

Sergei

**Comment by jpsglouzon** [comment]
Dear @spond,
Regarding the example, i realize that i made a mistake in the provided annotation.csv. In fact CCCvd have to replaced by CCCVd. That's why it's not colored properly. Clusters are typically subtrees and it would be nice to color the corresponding subtrees:
![tree](https://cloud.githubusercontent.com/assets/17144693/13692543/618d9772-e710-11e5-8422-28bc3ecdb3bd.png)

Thanks,
JP

**Comment by spond** [comment]
Hi @jpsglouzon,

OK, in other words you want to color internal branches if and only if **all** of their descendants belong to a cluster, correct?

Sergei

**Comment by spond** [comment]
Dear @jpsglouzon,

I updated http://bl.ocks.org/spond/dbc459acfaa6f134c67d to color internal branches as well. 

Sergei

**Comment by jpsglouzon** [comment]
Great! Thank your very much Sergei.
JP
