### ISSUE TITLE
Problem trying to host on Github Pages

### ISSUE THREAD

**Issue by hannah-fisher** [veg/phylotree.js#205]
Hi,

I am trying to use Phylotree.js in a website hosted on Github Pages. I am finding that when I open the page locally it works, and when I run a local server and open it it works, but on the page hosted on Github Pages the tree does not show up. From what I can tell, it seems like the svg is being created, but then the tree is not being displayed on it. 
Any idea why this might be occuring, and how to fix it? 

Thank you.

**Comment by gaurav** [comment]
Hi Hannah! Could you please add a link to the Github Pages website or the repository you are publishing it from? This problem might be easiest to diagnose if we could poke with the source code directly.

**Comment by hannah-fisher** [comment]
Yeah. I ended up just putting in the code from the hello world example and even that wasnt working. Here is the link to the page: https://hannah-fisher.github.io/FAVITESWebTools/TreeN93-Distance/test.html. And here is for the code: https://github.com/hannah-fisher/FAVITESWebTools/blob/master/TreeN93-Distance/test.html. Thank you.

**Comment by stephenshank** [comment]
Dear @hannah-fisher,

The issue is shown in the developer tools console (see below). Github pages is served over https, while our static assets (JavaScript bundles and stylesheets) are served over http. This is disallowed by modern web standards for security purposes.

While this is outside of the scope of phylotree, a simple solution would be to host all required static assets yourself, perhaps by including them in the repo and adjusting associated URLs.

![image](https://user-images.githubusercontent.com/8673708/87581986-c7137280-c6a7-11ea-9b06-7ae7d2d95363.png)


Best,
Stephen

**Comment by hannah-fisher** [comment]
Thank you for the explanation, I will try that.

**Comment by gaurav** [comment]
@stephenshank: I notice that the SSL certificate for Phylotree appears to be misconfigured (see https://phylotree.hyphy.org). If we could get that fixed, we could change https://veg.github.io/phylotree.js/phylotree.js to redirect to https://phylotree.hyphy.org/phylotree.js, which would eliminate this problem.

**Comment by hannah-fisher** [comment]
Hosting the phylotree files myself made it work, thank you so much!

**Comment by stephenshank** [comment]
You're welcome, glad it worked!
