### ISSUE TITLE
Collapse all nodes except for important nodes

### ISSUE THREAD

**Issue by santule** [veg/phylotree.js#415]
Hello,

I am trying to implement automated node collapsing on large trees. When the tree is initially loaded, I want to collapse all nodes except for important nodes. I design this by saying if the leaf node A is important then keep all its ancestors uncollapsed till the root. I defined important nodes as a part of the annotation.json file which is supplied along with the tree file. I have implemented the solution using toggleCollapse and tree traverse_and_compute function. It works but gives some error. I think the error may be due to collapsing a parent whose child is already collapse? am not sure why this is happening and if there is better way for me to code for this functionality.

// Construct a tree
`
tree = new phylotree.phylotree(test_string);
 global_tree = tree;`
  
// Get the list of nodes not to be collapsed         
`
 nodes_not_collpase = do_not_collapse(tree,metadata["important"]);
 `

// Traverse the tree and collapse everything except for the important nodes
`tree.traverse_and_compute ((n) => {
           if ((nodes_not_collpase.includes(n.data.name) == false) && (tree.isLeafNode(n) == false)){ 
                  rendered_tree.toggleCollapse(n);
            }
       });
       rendered_tree.update();`

TREE:
<img width="1039" alt="Screen Shot 2022-04-12 at 3 53 51 pm" src="https://user-images.githubusercontent.com/20509836/162890396-5ace3907-64c6-47a8-9867-0da3be26e643.png">

ERROR:
<img width="591" alt="Screen Shot 2022-04-12 at 3 53 38 pm" src="https://user-images.githubusercontent.com/20509836/162890312-e4e354e5-2ea5-41f3-8fc4-a405c04084da.png">

Thank you for your help.

**Comment by santule** [comment]
I found the root cause of the issue. If you run multiple collapse on the clade recursively as you travel upwards the tree, it cannot find the attributes. I handled this. Will close this issue.

**Comment by nazinorbi** [comment]
Dear santule! I need your help. I would like to implement something similar to what you described in the post. The difference is that I would like to call the toggleCollapse(d) function from my own context menu. My code is:
`this.globalVariable.tree = new phylotree.phylotree(test_string);`
.....
`self.globalVariable.tree.phylotree.toggleCollapse(d)`

here is your js error message domb (jquery-3.7.1.min.js:2 jQuery.Deferred exception: Cannot read properties of undefined (reading 'toggleCollapse')

What could be the error and how can I get and use the function? Can you share the js file containing your solution so that I can learn from it?
Thanks.
